// Daily refresh entrypoint (run as a Cloud Run Job on a Cloud Scheduler cron).
//
// Reuses the *same scripts and system* as the upstream sorter:
//   1. Clone the upstream scraper scripts at a pinned ref.
//   2. Lay them out as they expect, seeded with a baseline `data/` (incl.
//      `data/raw`) so the incremental scripts have a starting point.
//   3. Run upstream `update.ts` (DATA_ONLY) + `parse-discography`.
//   4. Assemble the canonical JSON and publish per-entity files to the data repo
//      (ll-music-data), which GitHub Pages serves to the frontend.
//
// NOTE: the scrape step hits external sites (lovelive-anime.jp, ll-fans.jp, the
// fandom wiki) and depends on the upstream repos' layout, so it can only be
// validated in the live Cloud Run Job. The build/load below is independent.
import { $ } from "bun";
import { cp, mkdir, rm } from "fs/promises";
import { join } from "path";
import { buildDataset, datasetCounts } from "./build-dataset";
import { publishData } from "./publish-data";

const SCRAPER_REPO =
  process.env.SCRAPER_REPO ?? "https://github.com/hamzaabamboo/ll-sorter-scripts";
const SCRAPER_REF =
  process.env.SCRAPER_REF ?? "9ae76c2d7ba8cca2003f85a8846eb0e61440813a";
// Baseline data the incremental scrapers diff against (committed data + raw/).
const SEED_REPO =
  process.env.SEED_REPO ?? "https://github.com/hamproductions/the-sorter";
const SEED_REF = process.env.SEED_REF ?? "main";

// The job needs a GitHub token with READ on the private scraper repo (to clone
// it) and WRITE on the data repo (publish-data.ts pushes the JSON there).
// Provide via Secret Manager (see setup-gcp.sh). Never logged.
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

// Inject token auth into an https github URL for cloning a private repo.
function authedUrl(repo: string): string {
  if (!GITHUB_TOKEN) return repo;
  return repo.replace("https://", `https://x-access-token:${GITHUB_TOKEN}@`);
}

// Strip the token from any text before it reaches logs.
function redact(text: string): string {
  return GITHUB_TOKEN ? text.split(GITHUB_TOKEN).join("***") : text;
}

// Note: series-info.json and series.json are not regenerated by the scrapers;
// they are carried forward from the seed repo clone (rarely change).

const WORK = join(import.meta.dir, ".work");

async function prepareWorkspace() {
  await rm(WORK, { recursive: true, force: true });
  // Layout the scrapers expect: scripts at <root>/scraper/scripts, data at
  // <root>/data (scripts reference ../../data from their own dir).
  const scriptsDir = join(WORK, "scraper", "scripts");
  const dataDir = join(WORK, "data");
  await mkdir(scriptsDir, { recursive: true });
  await mkdir(join(dataDir, "raw"), { recursive: true });

  // Full clone (the scraper repo is small) so we can checkout the pinned SHA —
  // GitHub rejects `fetch --depth 1 <sha>` for arbitrary commits. The scraper
  // repo is private; authedUrl adds the token when present.
  await $`git clone ${authedUrl(SCRAPER_REPO)} ${scriptsDir}`.quiet();
  await $`git -C ${scriptsDir} checkout ${SCRAPER_REF}`.quiet();

  // Baseline data (incl. raw/) so incremental scrapers work.
  const seed = join(WORK, "seed");
  await $`git clone --depth 1 --branch ${SEED_REF} ${SEED_REPO} ${seed}`.quiet();
  await cp(join(seed, "data"), dataDir, { recursive: true });

  return { scriptsDir, dataDir };
}

async function runScrapers(scriptsDir: string) {
  await $`DATA_ONLY=1 bun run ${join(scriptsDir, "update.ts")}`.cwd(scriptsDir);
  // parse-discography isn't in the upstream default pipeline; run it so album
  // (discography) data refreshes from the freshly-fetched raw data.
  await $`bun run ${join(scriptsDir, "parse-discography.ts")}`.cwd(scriptsDir);
}

async function main() {
  const generatedAt = new Date().toISOString();
  try {
    console.log("Preparing workspace + cloning scrapers...");
    const { scriptsDir, dataDir } = await prepareWorkspace();

    console.log("Running scrapers (this hits external sites)...");
    await runScrapers(scriptsDir);

    console.log("Building dataset...");
    const dataset = await buildDataset(dataDir, generatedAt);
    const counts = datasetCounts(dataset);
    console.log("Counts:", counts);

    console.log("Publishing per-entity JSON to the data repo...");
    await publishData(dataset, counts);

    console.log("Refresh complete:", counts);
  } catch (err) {
    console.error("Refresh failed:", redact(err instanceof Error ? err.message : String(err)));
    // Bun's ShellError carries the failed command's stderr/stdout (redacted).
    const e = err as { stderr?: Buffer; stdout?: Buffer };
    if (e?.stderr) console.error("stderr:", redact(e.stderr.toString()));
    if (e?.stdout) console.error("stdout:", redact(e.stdout.toString()));
    process.exitCode = 1;
  } finally {
    await rm(WORK, { recursive: true, force: true }).catch(() => {});
  }
}

await main();
