// Daily refresh entrypoint (run as a Cloud Run Job on a Cloud Scheduler cron).
//
// Reuses the *same scripts and system* as the upstream sorter:
//   1. Clone the upstream scraper scripts at a pinned ref.
//   2. Lay them out as they expect, seeded with a baseline `data/` (incl.
//      `data/raw`) so the incremental scripts have a starting point.
//   3. Run upstream `update.ts` (DATA_ONLY) + `parse-discography`.
//   4. Assemble the canonical JSON into one dataset and upload it to GCS.
//
// NOTE: the scrape step hits external sites (lovelive-anime.jp, ll-fans.jp, the
// fandom wiki) and depends on the upstream repos' layout, so it can only be
// validated in the live Cloud Run Job. The build/upload below is independent.
import { $ } from "bun";
import { cp, mkdir, rm } from "fs/promises";
import { join } from "path";
import { buildDataset, datasetCounts } from "./build-dataset";
import { uploadJson } from "./gcs";

const SCRAPER_REPO =
  process.env.SCRAPER_REPO ?? "https://github.com/hamzaabamboo/ll-sorter-scripts";
const SCRAPER_REF =
  process.env.SCRAPER_REF ?? "9ae76c2d7ba8cca2003f85a8846eb0e61440813a";
// Baseline data the incremental scrapers diff against (committed data + raw/).
const SEED_REPO =
  process.env.SEED_REPO ?? "https://github.com/hamproductions/the-sorter";
const SEED_REF = process.env.SEED_REF ?? "main";

const GCS_BUCKET = process.env.GCS_BUCKET;
if (!GCS_BUCKET) throw new Error("GCS_BUCKET is not set");

// Note: series-info.json and series.json are not regenerated by the scrapers;
// they are carried forward from the seed repo clone (rarely change).

const WORK = join(import.meta.dir, ".work");

async function prepareWorkspace() {
  await rm(WORK, { recursive: true, force: true });
  // Layout the scrapers expect: scripts at <root>/scraper/scripts, data at
  // <root>/data (scripts reference ../../data from their own dir).
  const scriptsDir = join(WORK, "scraper", "scripts");
  const dataDir = join(WORK, "data");
  await mkdir(scriptsDir, { recursive: true });
  await mkdir(join(dataDir, "raw"), { recursive: true });

  await $`git clone --depth 1 ${SCRAPER_REPO} ${scriptsDir}`.quiet();
  await $`git -C ${scriptsDir} fetch --depth 1 origin ${SCRAPER_REF}`.quiet();
  await $`git -C ${scriptsDir} checkout ${SCRAPER_REF}`.quiet();

  // Baseline data (incl. raw/) so incremental scrapers work.
  const seed = join(WORK, "seed");
  await $`git clone --depth 1 --branch ${SEED_REF} ${SEED_REPO} ${seed}`.quiet();
  await cp(join(seed, "data"), dataDir, { recursive: true });

  return { scriptsDir, dataDir };
}

async function runScrapers(scriptsDir: string) {
  await $`DATA_ONLY=1 bun run ${join(scriptsDir, "update.ts")}`.cwd(scriptsDir);
  // parse-discography isn't in the upstream default pipeline; run it so album
  // (discography) data refreshes from the freshly-fetched raw data.
  await $`bun run ${join(scriptsDir, "parse-discography.ts")}`.cwd(scriptsDir);
}

async function main() {
  const generatedAt = new Date().toISOString();
  try {
    console.log("Preparing workspace + cloning scrapers...");
    const { scriptsDir, dataDir } = await prepareWorkspace();

    console.log("Running scrapers (this hits external sites)...");
    await runScrapers(scriptsDir);

    console.log("Building dataset...");
    const dataset = await buildDataset(dataDir, generatedAt);
    console.log("Counts:", datasetCounts(dataset));

    console.log(`Uploading to gs://${GCS_BUCKET}/dataset.json ...`);
    await uploadJson(GCS_BUCKET, "dataset.json", dataset);

    console.log("Refresh complete.");
  } catch (err) {
    console.error("Refresh failed:", err instanceof Error ? err.message : err);
    process.exitCode = 1;
  } finally {
    await rm(WORK, { recursive: true, force: true }).catch(() => {});
  }
}

await main();
