// Daily refresh entrypoint (run as a Cloud Run Job on a Cloud Scheduler cron).
//
// It reuses the *same scripts and system* as the upstream sorter:
//   1. Clone the upstream scraper scripts at a pinned ref.
//   2. Lay them out in the directory structure they expect, seeded with a
//      baseline `data/` (incl. `data/raw`) so the incremental scripts have a
//      starting point.
//   3. Run the upstream `update.ts` (DATA_ONLY path) to fetch fresh data, plus
//      `parse-discography` (not in the upstream default pipeline) so album data
//      refreshes too.
//   4. Load the resulting canonical JSON into Postgres.
//
// NOTE: the scrape step hits external sites (lovelive-anime.jp, ll-fans.jp,
// the fandom wiki) and depends on the upstream repos' exact layout, so it can
// only be validated in the live Cloud Run Job (not in CI / the sandbox). The
// DB/API/ingestion layers below it are environment-independent.
import { $ } from "bun";
import { cp, mkdir, rm } from "fs/promises";
import { join } from "path";
import { sql } from "./db";
import { loadDataDir } from "./load-to-db";

const SCRAPER_REPO =
  process.env.SCRAPER_REPO ?? "https://github.com/hamzaabamboo/ll-sorter-scripts";
const SCRAPER_REF =
  process.env.SCRAPER_REF ?? "9ae76c2d7ba8cca2003f85a8846eb0e61440813a";
// Baseline data the incremental scrapers diff against (committed data + raw/).
const SEED_REPO =
  process.env.SEED_REPO ?? "https://github.com/hamproductions/the-sorter";
const SEED_REF = process.env.SEED_REF ?? "main";

// Note: series-info.json and series.json are not regenerated by the scrapers;
// they are carried forward from the seed repo clone (rarely change).

const WORK = join(import.meta.dir, ".work");

async function applySchema() {
  const schema = await Bun.file(join(import.meta.dir, "schema.sql")).text();
  await sql.unsafe(schema);
}

async function prepareWorkspace() {
  await rm(WORK, { recursive: true, force: true });
  // Layout the scrapers expect: scripts at <root>/scraper/scripts, data at
  // <root>/data (scripts reference ../../data from their own dir).
  const scriptsDir = join(WORK, "scraper", "scripts");
  const dataDir = join(WORK, "data");
  await mkdir(scriptsDir, { recursive: true });
  await mkdir(join(dataDir, "raw"), { recursive: true });

  // Scraper scripts (pinned).
  await $`git clone --depth 1 ${SCRAPER_REPO} ${scriptsDir}`.quiet();
  await $`git -C ${scriptsDir} fetch --depth 1 origin ${SCRAPER_REF}`.quiet();
  await $`git -C ${scriptsDir} checkout ${SCRAPER_REF}`.quiet();

  // Baseline data (incl. raw/) from the seed repo so incremental scripts work.
  const seed = join(WORK, "seed");
  await $`git clone --depth 1 --branch ${SEED_REF} ${SEED_REPO} ${seed}`.quiet();
  await cp(join(seed, "data"), dataDir, { recursive: true });

  return { scriptsDir, dataDir };
}

async function runScrapers(scriptsDir: string) {
  // DATA_ONLY=1 runs the data scrapers and skips asset/image generation.
  await $`DATA_ONLY=1 bun run ${join(scriptsDir, "update.ts")}`.cwd(scriptsDir);
  // parse-discography is not in the upstream default pipeline; run it so album
  // (discography) data refreshes from the freshly-fetched raw data.
  await $`bun run ${join(scriptsDir, "parse-discography.ts")}`.cwd(scriptsDir);
}

async function main() {
  console.log("Applying schema...");
  await applySchema();

  const [build] =
    await sql`INSERT INTO builds (status, source_ref) VALUES ('running', ${SCRAPER_REF}) RETURNING id`;
  const buildId = build.id;

  try {
    console.log("Preparing workspace + cloning scrapers...");
    const { scriptsDir, dataDir } = await prepareWorkspace();

    console.log("Running scrapers (this hits external sites)...");
    await runScrapers(scriptsDir);

    console.log("Loading canonical data into Postgres...");
    const counts = await loadDataDir(dataDir);

    await sql`
      UPDATE builds
        SET status = 'success', finished_at = now(), counts = ${JSON.stringify(counts)}::jsonb
      WHERE id = ${buildId}
    `;
    console.log("Refresh complete:", counts);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await sql`
      UPDATE builds
        SET status = 'failed', finished_at = now(), error = ${message}
      WHERE id = ${buildId}
    `;
    console.error("Refresh failed:", message);
    process.exitCode = 1;
  } finally {
    await rm(WORK, { recursive: true, force: true }).catch(() => {});
    await sql.end();
  }
}

await main();
